// <auto-generated />
namespace DealDouble.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class identity_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identity_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202204080725129_identity_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
