// <auto-generated />
namespace DealDouble.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class added_Validations_AuctionEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Validations_AuctionEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202204071658383_added_Validations_AuctionEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
