// <auto-generated />
namespace DealDouble.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_auctionpicture_baseentity_picture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_auctionpicture_baseentity_picture));
        
        string IMigrationMetadata.Id
        {
            get { return "202204050944122_added_auctionpicture_baseentity_picture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
