// <auto-generated />
namespace DealDouble.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class identity_Models_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identity_Models_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "202204111014488_identity_Models_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
